packages:
  - apps/*

catalog:
  '@egoist/tailwindcss-icons': ^1.9.0
  '@headlessui/react': ^2.2.8
  '@headlessui/tailwindcss': ^0.2.2
  '@iconify-json/fa6-brands': ^1.2.6
  '@react-router/cloudflare': ^7.9.1
  '@react-router/dev': ^7.9.1
  '@react-router/fs-routes': ^7.9.1
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.13
  '@total-typescript/ts-reset': ^0.6.1
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  clsx: ^2.1.1
  es-toolkit: ^1.39.10
  react: ^19.1.1
  react-dom: ^19.1.1
  react-router: ^7.9.1
  react-scan: ^0.4.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  vite: ^7.1.5
  zustand: ^5.0.8
