name: Publish Docs

on:
  push:
    paths:
      - 'website/**'
  pull_request:
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run a build step here
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
            node-version-file: '.nvmrc'
            cache: 'pnpm'
            cache-dependency-path: 'pnpm-lock.yaml'

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Website
        run: cd website && pnpm run build

      # Run a action to publish docs
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: website
          command: pages deplooy build/client --project-name=furiganamaker